import type { Metadata } from "next";
import LegalPage from "@/components/LegalPage";

export const metadata: Metadata = { title: "Terms of Service — ApnaSite AI" };

// DRAFT terms — written in plain language for review by the site owner.
// Not legal advice; have a professional review before real payments.
export default function TermsPage() {
  return (
    <LegalPage title="Terms of Service">
      <h2>What ApnaSite is</h2>
      <p>
        ApnaSite AI turns your description of your business into a simple website you can edit and
        publish. It&apos;s built for small shop owners. By creating an account (logging in with
        your email) you agree to these terms.
      </p>

      <h2>Your content, your responsibility</h2>
      <p>
        The words on your site are generated by AI from your description, and you can edit
        everything before publishing. <strong>You must check what gets published.</strong> AI can
        make mistakes — wrong hours, invented claims, awkward phrasing. Whatever is live on your
        site is your responsibility, including prices, offers, and legal claims about your
        products.
      </p>
      <p>
        Don&apos;t publish content that is illegal, misleading, infringes someone else&apos;s
        trademarks or copyrights, or impersonates another business. We can unpublish or remove
        sites that do.
      </p>

      <h2>Your account</h2>
      <p>
        You log in with a code sent to your email — keep access to that inbox secure. You can
        delete your sites at any time from the dashboard.
      </p>

      <h2>Plans and payment</h2>
      <p>
        The Free plan includes one published site with a small &quot;Made with ApnaSite&quot;
        badge. The Pro plan (₹199/month) allows up to five published sites without the badge.
        Payments are processed by Razorpay — we never see or store your card details. You can
        cancel anytime; your sites stay up until the end of the paid period, after which the free
        plan limits apply again.
      </p>

      <h2>Service, as-is</h2>
      <p>
        ApnaSite is provided as-is, without uptime guarantees. We work hard to keep your sites
        online, but we&apos;re not liable for lost business from downtime or errors. We may change
        or discontinue features with reasonable notice.
      </p>

      <h2>Contact</h2>
      <p>
        Questions about these terms: <strong>[contact email — to be added]</strong>
      </p>
    </LegalPage>
  );
}
