import { ZipArchive } from "archiver";
import type { Archiver } from "archiver";
import type { StorefrontData } from "./types";
import { renderStorefrontHTML } from "@/lib/renderSite";

function collectBuffer(archive: Archiver): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    archive.on("data", (chunk: Buffer) => chunks.push(chunk));
    archive.on("end", () => resolve(Buffer.concat(chunks)));
    archive.on("error", reject);
  });
}

export async function generateSiteZip(data: StorefrontData): Promise<Buffer> {
  const html = renderStorefrontHTML(data, { showBadge: false });

  const archive = new ZipArchive({ zlib: { level: 9 } });
  const bufferPromise = collectBuffer(archive);

  archive.append(html, { name: "index.html" });

  const readme = [
    `${data.shopName} — Website Export`,
    "=".repeat(40),
    "",
    "This ZIP contains your website as a single HTML file.",
    "",
    "To view: open index.html in any web browser.",
    "To host: upload index.html to any static hosting service",
    "          (Netlify, Vercel, GitHub Pages, or your own server).",
    "",
    "Notes:",
    "- The site is fully self-contained (all styles are inline).",
    "- Images hosted on ApnaSite will still load if the site is live.",
    "- To update your site, edit it on ApnaSite AI and re-export.",
    "",
    "Generated by ApnaSite AI — apnasite.in",
  ].join("\n");

  archive.append(readme, { name: "README.txt" });

  await archive.finalize();
  return bufferPromise;
}
